version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: setup
          command: |
            cd backend
            make setup
      - run:
          name: install dependencies
          command: |
            cd backend
            make install
      - run:
          name: run test
          command: |
            cd backend
            make test
      - run:
          name: run lint
          command: |
            cd backend
            make lint
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip python3
      - attach_workspace:
          at: ~/
      - run:
          name: eksctl Installation
          command: |
            # curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
      - run:
          name: eksctl create cluster
          command: |
            export DOCKER_PATH=$DOCKER_PATH

            eksctl create cluster --name eksctl-casptone --region=us-east-1 --profile casptone-project
            kubectl get nodes --profile casptone-project
            kubectl create deploy capstone-project-eks --image="${DOCKER_PATH}/capstone-project"
            kubectl get deploy,rs,svc,pods
            kubectl port-forward deployment.apps/capstone-project-eks 3001:3000

workflows:
  default:
    jobs:
      # - build
      # - deploy:
          # requires: [build]
      - deploy