version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: setup
          command: |
            cd backend
            make setup
      - run:
          name: install dependencies
          command: |
            cd backend
            make install
      - run:
          name: run test
          command: |
            cd backend
            make test
      - run:
          name: run lint
          command: |
            cd backend
            make lint
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  push:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: 
          name: docker build and push
          command: |
            export DOCKER_PATH=$DOCKER_PATH

            docker build --tag "capstone-project-${CIRCLE_WORKFLOW_ID:0:7}" .
            docker image list
            
            echo "Docker ID and Image: ${DOCKER_PATH}"
            cat $DOCKER_PASS | docker login --username $DOCKER_PATH --password-stdin
            docker image tag "capstone-project-${CIRCLE_WORKFLOW_ID:0:7}" "${DOCKER_PATH}/capstone-project-${CIRCLE_WORKFLOW_ID:0:7}"
            docker image push "${DOCKER_PATH}/capstone-project-${CIRCLE_WORKFLOW_ID:0:7}"
  deploy:
    docker:
      - image: python:3.9.16
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            pip3 install awscli
            apt-get update -y
            # yum install -y tar gzip
      - attach_workspace:
          at: ~/
      - run:
          name: eksctl Installation
          command: |
            # curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
      - run:
          name: kubectl Installation
          command: |
            # apt update && apt upgrade
            # yum install sudo
            
            # apt-get update
            # apt-get install -y ca-certificates curl
            # apt-get install -y apt-transport-https
            # mkdir /etc/apt/keyrings
            # curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
            # echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
            # apt-get update
            # apt-get install -y kubectl

            # v2
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            # chmod +x kubectl
            # mkdir -p ~/.local/bin
            # mv ./kubectl ~/.local/bin/kubectl
            kubectl version --client
      - run:
          name: eksctl create cluster
          command: |
            export DOCKER_PATH=$DOCKER_PATH

            # eksctl create cluster --name eksctl-casptone --region=us-east-1
            kubectl get nodes 
            kubectl create deploy capstone-project-eks --image="${DOCKER_PATH}/capstone-project-${CIRCLE_WORKFLOW_ID:0:7}"
            kubectl get deploy,rs,svc,pods
            kubectl port-forward deployment.apps/capstone-project-eks 3001:3000

workflows:
  default:
    jobs:
      # - build
      # - deploy:
          # requires: [build]
      - deploy